// Copies the shared rules engine into supabase/functions/_shared/engine so the Deno
// Edge Functions bundle exactly the same code the app runs. (Engine imports use explicit
// .ts extensions, which Deno, Vitest and Metro all understand.)
import { cpSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'packages/engine/src');
const dest = join(root, 'supabase/functions/_shared/engine');
rmSync(dest, { recursive: true, force: true });
mkdirSync(dest, { recursive: true });
cpSync(src, dest, { recursive: true });
writeFileSync(join(dest, 'README.md'), 'Generated by scripts/sync-engine.mjs — do not edit. Source: packages/engine/src\n');
console.log(`Engine synced → ${dest}`);
