// Pixel icons & avatars. In UI icons, 'K' maps to the theme ink and 'm' to the accent fill,
// so the same sprite works on light, dark and colored buttons.
import type { Sprite } from './canvas';

export const RESOURCE_SPRITES: Record<'timber' | 'clay' | 'fleece' | 'grain' | 'stone', Sprite> = {
  timber: [
    '..KKKKKKKKK.',
    '.KOKbbbbbbbK',
    '.KoOKbbBbbbK',
    '.KOKbbbbbbbK',
    'KKKKKKKKKKK.',
    'KOKbbbbbbbK.',
    'KoOKbbbBbbK.',
    'KOKbbbbbbbK.',
    '.KKKKKKKKK..',
  ],
  clay: [
    '...KKKKKKKKK',
    '..KrrrrrrrRK',
    '.KrrrrrrrRRK',
    'KKKKKKKKKRRK',
    'KrrrrrrrKRRK',
    'KrqqrrrrKRK.',
    'KrrrrrrrKK..',
    'KKKKKKKKK...',
  ],
  fleece: [
    '...KKKK.....',
    '..KWWWWKKK..',
    '.KWWwWWKEEK.',
    '.KWwWWwKEWK.',
    '.KWWWWWKEEK.',
    '..KKKKKKKK..',
    '..K.K..K.K..',
  ],
  grain: [
    '.Y...Y...Y..',
    'YyY.YyY.YyY.',
    '.Y..YyY..Y..',
    'YyY..y..YyY.',
    '..yY.o.Yy...',
    '....ooo.....',
    '...KhhhK....',
    '....ooo.....',
    '...o.o.o....',
    '..o..o..o...',
  ],
  stone: [
    '....KKKK....',
    '..KKssSsKK..',
    '.KsssSSsstK.',
    'KssssssstttK',
    'KsssssttttTK',
    '.KsstttTTTK.',
    '..KKKKKKKK..',
  ],
};

export const RESOURCE_PALETTE = {
  K: '#2A1F3D',
  O: '#F1C98E',
  o: '#D9A35F',
  b: '#B9783F',
  B: '#8B5A2B',
  r: '#E08A5C',
  R: '#A9502A',
  q: '#FFD2B0',
  W: '#FFFFFF',
  w: '#C9D0DA',
  E: '#3B2D52',
  Y: '#FFE27A',
  y: '#D9A82A',
  h: '#EF476F',
  s: '#B2B9C8',
  S: '#E9ECF2',
  t: '#7F889B',
  T: '#5E6678',
};

export const ICON_SPRITES = {
  dice: [
    '.KKKKKKKKKK.',
    'KmmmmmmmmmmK',
    'KmKKmmmmKKmK',
    'KmKKmmmmKKmK',
    'KmmmmmmmmmmK',
    'KmmmmKKmmmmK',
    'KmmmmKKmmmmK',
    'KmmmmmmmmmmK',
    'KmKKmmmmKKmK',
    'KmKKmmmmKKmK',
    'KmmmmmmmmmmK',
    '.KKKKKKKKKK.',
  ],
  hammer: [
    '.KKKKKKKK.',
    'KmmmmmmmmK',
    'KmmmmmmmmK',
    '.KKKKbKKK.',
    '....KbK...',
    '....KbK...',
    '....KbK...',
    '....KbK...',
    '....KbK...',
    '....KKK...',
  ],
  trade: [
    '......KK....',
    'KKKKKKKmK...',
    'KmmmmmmmmK..',
    'KKKKKKKmK...',
    '......KK....',
    '............',
    '....KK......',
    '...KlKKKKKKK',
    '..KllllllllK',
    '...KlKKKKKKK',
    '....KK......',
  ],
  fortune: [
    '.KKKKKKKK.',
    'KmmmmmmmmK',
    'KmmmKKmmmK',
    'KmmKWWKmmK',
    'KmKWWWWKmK',
    'KmmKWWKmmK',
    'KmmmKKmmmK',
    'KmmmmmmmmK',
    'KmmmmmmmmK',
    '.KKKKKKKK.',
  ],
  flag: [
    'KK.........',
    'KmKKKKKK...',
    'KmmmmmmmK..',
    'KmmmmmmmmK.',
    'KmmmmmmmK..',
    'KmKKKKKK...',
    'KK.........',
    'KK.........',
    'KK.........',
    'KKKK.......',
  ],
  bell: ['....KK....', '...KmmK...', '..KmmmmK..', '..KmmmmK..', '.KmmmmmmK.', 'KKKKKKKKKK', '....KK....'],
  friends: [
    '..KKK.......',
    '.KmmmK.KKK..',
    '.KmmmKKlllK.',
    '..KKK.KlllK.',
    '.KKKKK.KKK..',
    'KmmmmmKKKKK.',
    'KmmmmmKllllK',
    'KmmmmmKllllK',
    'KKKKKKKKKKKK',
  ],
  gear: [
    '....KKKK....',
    '..K.KmmK.K..',
    '.KmKmmmmKmK.',
    '..KmmmmmmK..',
    'KKmmKKKKmmKK',
    'KmmmKWWKmmmK',
    'KmmmKWWKmmmK',
    'KKmmKKKKmmKK',
    '..KmmmmmmK..',
    '.KmKmmmmKmK.',
    '..K.KmmK.K..',
    '....KKKK....',
  ],
  plus: ['...KK...', '...KK...', '...KK...', 'KKKKKKKK', 'KKKKKKKK', '...KK...', '...KK...', '...KK...'],
  check: ['........KK', '.......KKK', '......KKK.', 'KK...KKK..', 'KKK.KKK...', '.KKKKK....', '..KKK.....', '...K......'],
  close: ['KK....KK', 'KKK..KKK', '.KKKKKK.', '..KKKK..', '..KKKK..', '.KKKKKK.', 'KKK..KKK', 'KK....KK'],
  back: ['....KK', '...KKK', '..KKK.', '.KKK..', 'KKK...', '.KKK..', '..KKK.', '...KKK', '....KK'],
  crown: ['K....K....K', 'KK..KmK..KK', 'KmKKmmmKKmK', 'KmmmmmmmmmK', 'KmmhmmmhmmK', 'KmmmmmmmmmK', 'KKKKKKKKKKK'],
  scroll: [
    '.KKKKKKKKK.',
    'KWWWWWWWWWK',
    'KWKKKKKKWWK',
    'KWWWWWWWWWK',
    'KWKKKKKWWWK',
    'KWWWWWWWWWK',
    'KWKKKKKKWWK',
    'KWWWWWWWWWK',
    'KmmmmmmmmmK',
    '.KKKKKKKKK.',
  ],
  boat: [
    '.....K......',
    '.....KK.....',
    '.....KWK....',
    '.....KWWK...',
    '.....KWWWK..',
    '.....KWWWWK.',
    '.....KKKKKKK',
    'KKKKKKKKKKKK',
    '.KmmmmmmmmK.',
    '..KmmmmmmK..',
    '...KKKKKK...',
  ],
  share: ['.....KK.....', '....KKKK....', '...KKKKKK...', '.....KK.....', '.....KK.....', 'KK...KK...KK', 'KK........KK', 'KK........KK', 'KKKKKKKKKKKK'],
  clock: [
    '...KKKKK...',
    '..KmmmmmK..',
    '.KmmmKmmmK.',
    'KmmmmKmmmmK',
    'KmmmmKmmmmK',
    'KmmmmKKKmmK',
    'KmmmmmmmmmK',
    '.KmmmmmmmK.',
    '..KmmmmmK..',
    '...KKKKK...',
  ],
  trail: [
    '........KKK',
    '.......KmmK',
    '......KmmK.',
    '.....KmmK..',
    '....KmmK...',
    '...KmmK....',
    '..KmmK.....',
    '.KmmK......',
    'KmmK.......',
    'KKK........',
  ],
  shield: ['KKKKKKKKKK', 'KmmmmmmmmK', 'KmmmKKmmmK', 'KmmKllKmmK', 'KmmmKKmmmK', 'KmmmmmmmmK', '.KmmmmmmK.', '..KmmmmK..', '...KmmK...', '....KK....'],
  island: [
    '....K.K.....',
    '...KgKgK....',
    '..KgKbKgK...',
    '.....Kb.....',
    '.....Kb.....',
    '...KKKKKK...',
    '..KmmmmmmK..',
    'lKmmmmmmmmKl',
    'llllllllllll',
  ],
} satisfies Record<string, Sprite>;

export type IconName = keyof typeof ICON_SPRITES;

export const ICON_FIXED = { W: '#FFF8EA', l: '#1BA3A0', h: '#EF476F', b: '#8B5A2B', g: '#2F7D4F' };

// --- Avatars (16 wide) ----------------------------------------------------------

export const AVATAR_SPRITES: Record<string, Sprite> = {
  gull: [
    '......KKKK......',
    '....KKWWWWKK....',
    '...KWWWWWWWWK...',
    '..KWWWWWWKKWWK..',
    '..KWWWWWWKKWWKKK',
    '..KWWWWWWWWWWYYK',
    '..KWWWWWWWWWKKK.',
    '..KwWWWWWWWWK...',
    '..KwwWWWWWWWK...',
    '...KwwWWWWWK....',
    '....KKKKKKK.....',
  ],
  turtle: [
    '.....KKKK.......',
    '....KgggGK......',
    '...KgKgggGK.....',
    '...KgggggGK.....',
    '....KgggggK.....',
    '..KKKKKKKKKKK...',
    '.KnNnNnNnNnNnK..',
    'KnNnnnNnnnNnnNK.',
    'KNnnNnnnNnnNnnK.',
    '.KKKKKKKKKKKKK..',
    '..KgK......KgK..',
  ],
  crab: [
    '..KK........KK..',
    '.KhhK......KhhK.',
    '.KhK........KhK.',
    '..KhK.KKKK.KhK..',
    '...KhKWKKWKhK...',
    '....KKWKKWKK....',
    '...KhhhhhhhhK...',
    '..KhhhhhhhhhhK..',
    '..KhhhKKKKhhhK..',
    '...KhhhhhhhhK...',
    '..K.KKKKKKKK.K..',
    '.K..K..K..K..K..',
  ],
  puffin: [
    '.....KKKKK......',
    '....KKKKKKK.....',
    '...KKWWWKKKK....',
    '...KWWKWWKKKK...',
    '...KWWWWWammK...',
    '...KWWWWWaaaK...',
    '...KKWWWWWKK....',
    '..KKKWWWWWKKK...',
    '..KKKWWWWWKKK...',
    '...KKWWWWWKK....',
    '....KKKKKKK.....',
    '....aa...aa.....',
  ],
  otter: [
    '...KK......KK...',
    '..KbbK....KbbK..',
    '..KbbbKKKKbbbK..',
    '..KbbbbbbbbbbK..',
    '.KbbKKbbbbKKbbK.',
    '.KbbKWbbbbKWbbK.',
    '.KbbbbccccbbbbK.',
    '.KbbbcccKcccbbK.',
    '.KbbbccKKKccbbK.',
    '..KbbbccccbbbK..',
    '...KKbbbbbbKK...',
    '.....KKKKKK.....',
  ],
  whale: [
    '.....K..K.......',
    '......KK........',
    '.....K..K.......',
    '....KKKKKKKK....',
    '..KKLLLLLLLLKK..',
    '.KLLLLLLLLLLLLK.',
    'KLLLLLLLLKKLLLLK',
    'KLLLLLLLLKWLLLLK',
    'KLLLLLLLLLLLLLLK',
    'KccLccLccLccLLK.',
    '.KccccccccccKK..',
    '..KKKKKKKKKK....',
  ],
  octopus: [
    '.....KKKKKK.....',
    '...KKPPPPPPKK...',
    '..KPPPPPPPPPPK..',
    '..KPPKKPPKKPPK..',
    '..KPPKWPPKWPPK..',
    '..KPPPPPPPPPPK..',
    '..KPPPPKKPPPPK..',
    '...KPPPPPPPPK...',
    '..KPKPKPPKPKPK..',
    '.KPK.KPKKPK.KPK.',
    '.KK..KK..KK..KK.',
  ],
  seal: [
    '.....KKKKKK.....',
    '...KKsssssssKK..',
    '..KsssssssssssK.',
    '.KssKKssssKKsssK',
    '.KssKWssssKWsssK',
    '.KssssssssssssK.',
    '.KsKKssKKssKKsK.',
    '.KssssKKKKsssssK',
    '..KsssssssssssK.',
    '...KKsssssssKK..',
    '.....KKKKKKK....',
  ],
};

export const AVATAR_PALETTE = {
  K: '#2A1F3D',
  W: '#FFFFFF',
  w: '#C9D0DA',
  Y: '#FFB627',
  g: '#93CF5F',
  G: '#B4E37E',
  n: '#4F9D52',
  N: '#2E6B35',
  h: '#EF476F',
  a: '#FF8A3D',
  m: '#FFB627',
  b: '#A9744A',
  c: '#F1DDC4',
  L: '#3A7BD5',
  P: '#B56CC8',
  s: '#9AA3B5',
};
